### ISSUE TITLE
关于本项目的使用询问

### ISSUE THREAD

**Issue by rnmmr** [Zzzzzzyt/moegirl-dataset#1]
我正在做一个用Tag筛选来查找动漫人物的[网页工具](https://github.com/D4box/MACDB)，Tag对应的角色我自己暴力爬过了，目前正在收集角色对应图片的链接，想问下可以使用这个项目的吗，还有想问下萌百的访问频率限制是多少

**Comment by Zzzzzzyt** [comment]
用的话给个开源声明就行了(按照MIT协议来)，最好给个链接 谢谢:)
萌百是CC BY-SA-NC，bangumi是CC BY-SA，按要求署名

萌百api现在要申请robot权限的，我懒得搞，就直接爬网页了。萌百限速可能一秒一次吧，不清楚，我是3s一次，带上了自己的登录cookie的，可能限制松一点

你要的文件在moegirl/preprocess/和moegirl/crawler2
